/*
 * Copyright (c) 2026 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */

/* The BLE lifecycle flag must stay disabled when ZMK_BLE is absent. */
#define CONFIG_ZMK_RUNTIME_MACRO_DYNAMIC 1
#define CONFIG_ZMK_RUNTIME_MACRO_MAX_TEXT_LEN 64
#define CONFIG_ZMK_RUNTIME_MACRO_DYNAMIC_CLEAR_ON_USB_DISCONNECT 1
#define CONFIG_ZMK_RUNTIME_MACRO_DYNAMIC_CLEAR_ON_BLE_PROFILE_CHANGE 1
#define CONFIG_ZMK_RUNTIME_MACRO_DYNAMIC_CLEAR_ON_ENDPOINT_CHANGE 1

#include <zmk/runtime_macro_protocol.h>

#if ZMK_RUNTIME_MACRO_PROTOCOL_CAPABILITY_LIFECYCLE_FLAGS != \
    (ZMK_RUNTIME_MACRO_PROTOCOL_CAPABILITY_FIXED_LIFECYCLE_FLAGS | \
     ZMK_RUNTIME_MACRO_PROTOCOL_CAPABILITY_SUPPORTS_KEEP_AFTER_EXECUTE | \
     ZMK_RUNTIME_MACRO_PROTOCOL_CAPABILITY_CLEAR_ON_USB_DISCONNECT | \
     ZMK_RUNTIME_MACRO_PROTOCOL_CAPABILITY_CLEAR_ON_ENDPOINT_CHANGE)
#error "BLE lifecycle capability must be gated by CONFIG_ZMK_BLE"
#endif

int main(void) { return 0; }
