/*
 * Copyright (c) 2026 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */

#include <errno.h>
#include <stdint.h>

#include <dt-bindings/zmk/hid_usage.h>
#include <dt-bindings/zmk/hid_usage_pages.h>
#include <dt-bindings/zmk/modifiers.h>

#include <zmk/runtime_macro.h>

#define RUNTIME_MACRO_KEY(_id) ZMK_HID_USAGE(HID_USAGE_KEY, (_id))
#define RUNTIME_MACRO_SHIFTED_KEY(_id) APPLY_MODS(MOD_LSFT, RUNTIME_MACRO_KEY(_id))

/*
 * This is the US keyboard layout's ASCII mapping. A zero entry is invalid;
 * every valid keyboard usage is non-zero, so the same table can be used by
 * both Settings validation and the executor.
 */
static const uint32_t runtime_macro_ascii_map[128] = {
    ['\b'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_DELETE_BACKSPACE),
    ['\t'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_TAB),
    ['\n'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_RETURN_ENTER),
    [' '] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_SPACEBAR),

    ['!'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_1_AND_EXCLAMATION),
    ['"'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_APOSTROPHE_AND_QUOTE),
    ['#'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_3_AND_HASH),
    ['$'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_4_AND_DOLLAR),
    ['%'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_5_AND_PERCENT),
    ['&'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_7_AND_AMPERSAND),
    ['\''] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_APOSTROPHE_AND_QUOTE),
    ['('] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_9_AND_LEFT_PARENTHESIS),
    [')'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_0_AND_RIGHT_PARENTHESIS),
    ['*'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_8_AND_ASTERISK),
    ['+'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_EQUAL_AND_PLUS),
    [','] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_COMMA_AND_LESS_THAN),
    ['-'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_MINUS_AND_UNDERSCORE),
    ['.'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_PERIOD_AND_GREATER_THAN),
    ['/'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_SLASH_AND_QUESTION_MARK),
    [':'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_SEMICOLON_AND_COLON),
    [';'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_SEMICOLON_AND_COLON),
    ['<'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_COMMA_AND_LESS_THAN),
    ['='] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_EQUAL_AND_PLUS),
    ['>'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_PERIOD_AND_GREATER_THAN),
    ['?'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_SLASH_AND_QUESTION_MARK),
    ['@'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_2_AND_AT),
    ['['] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_LEFT_BRACKET_AND_LEFT_BRACE),
    ['\\'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_BACKSLASH_AND_PIPE),
    [']'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_RIGHT_BRACKET_AND_RIGHT_BRACE),
    ['^'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_6_AND_CARET),
    ['_'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_MINUS_AND_UNDERSCORE),
    ['`'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_GRAVE_ACCENT_AND_TILDE),
    ['{'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_LEFT_BRACKET_AND_LEFT_BRACE),
    ['|'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_BACKSLASH_AND_PIPE),
    ['}'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_RIGHT_BRACKET_AND_RIGHT_BRACE),
    ['~'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_GRAVE_ACCENT_AND_TILDE),

    ['0'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_0_AND_RIGHT_PARENTHESIS),
    ['1'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_1_AND_EXCLAMATION),
    ['2'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_2_AND_AT),
    ['3'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_3_AND_HASH),
    ['4'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_4_AND_DOLLAR),
    ['5'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_5_AND_PERCENT),
    ['6'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_6_AND_CARET),
    ['7'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_7_AND_AMPERSAND),
    ['8'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_8_AND_ASTERISK),
    ['9'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_9_AND_LEFT_PARENTHESIS),

    ['A'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_A),
    ['B'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_B),
    ['C'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_C),
    ['D'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_D),
    ['E'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_E),
    ['F'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_F),
    ['G'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_G),
    ['H'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_H),
    ['I'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_I),
    ['J'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_J),
    ['K'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_K),
    ['L'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_L),
    ['M'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_M),
    ['N'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_N),
    ['O'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_O),
    ['P'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_P),
    ['Q'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_Q),
    ['R'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_R),
    ['S'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_S),
    ['T'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_T),
    ['U'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_U),
    ['V'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_V),
    ['W'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_W),
    ['X'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_X),
    ['Y'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_Y),
    ['Z'] = RUNTIME_MACRO_SHIFTED_KEY(HID_USAGE_KEY_KEYBOARD_Z),

    ['a'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_A),
    ['b'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_B),
    ['c'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_C),
    ['d'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_D),
    ['e'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_E),
    ['f'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_F),
    ['g'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_G),
    ['h'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_H),
    ['i'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_I),
    ['j'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_J),
    ['k'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_K),
    ['l'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_L),
    ['m'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_M),
    ['n'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_N),
    ['o'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_O),
    ['p'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_P),
    ['q'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_Q),
    ['r'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_R),
    ['s'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_S),
    ['t'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_T),
    ['u'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_U),
    ['v'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_V),
    ['w'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_W),
    ['x'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_X),
    ['y'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_Y),
    ['z'] = RUNTIME_MACRO_KEY(HID_USAGE_KEY_KEYBOARD_Z),
};

int zmk_runtime_macro_ascii_to_keycode(uint8_t byte, uint32_t *encoded) {
    if (encoded == NULL ||
        byte >= sizeof(runtime_macro_ascii_map) / sizeof(runtime_macro_ascii_map[0]) ||
        runtime_macro_ascii_map[byte] == 0) {
        return -EINVAL;
    }

    *encoded = runtime_macro_ascii_map[byte];
    return 0;
}
